### ISSUE TITLE
Service Accounts (domain delegation)

### ISSUE THREAD

**Issue by respinoza** [Happyr/GoogleSiteAuthenticatorBundle#1]
Hello Tobias,

I was wondering if you are interested in adding support for Service Accounts to this bundle?

I know the main purpose for this bundle is to have server-side API calls without the need to pay for Google Apps but because we are using your Analytics bundle, specifically the fetch feature, it will be nice to have support for Service Accounts.

If you had tried this in the past or you have any ideas on what do you want to see, please let me know.
Initially I was thinking that in the getClient method specify the type of account, of course leave the current 'web application' type the default but add a 'service account'.

Thank you

**Comment by Nyholm** [comment]
Hey. 
Thank you for this issue. Of course we should have support for Service Accounts. 

I'm not sure how a Service Account differs in authentication. But yes, you could do something with `ClientProvider::getClient` or maybe add a `type` parameter to the `TokenConfig`. 

Like I said, I'm very open to this. If you submit a PR we can work together to finish this feature.

**Comment by respinoza** [comment]
Thank you for the reply.
I will start working on it and submit a PR and then we can discuss from there the approach.

**Comment by Nyholm** [comment]
Okey, Awesome!
