### ISSUE TITLE
Dependency Hell

### ISSUE THREAD

**Issue by pquerner** [Happyr/GoogleSiteAuthenticatorBundle#15]
I understand caching is fine, but why open yourself up to dependency hell ?
For the last hours I've been struggling for that simple thing: caching.

If you cache the access token, why not use a simple filesystem which is available in a PHPs default installation ?

I just want a simple cache to filesystem, but I have to install dozens of other bundles to give me this trivial command and still cannot get it to work, because caching bundles like to be abstract and want you to install more and more bundles all the time.

**Comment by Nyholm** [comment]
Im closing this due inactivity. 

For any one else seeing this issue: I dont want to reinvent caching. Using a PSR-6 will allow the user to have control over the cache.
